// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon May 06 14:34:57 2024

Memory Memory_inst
(
	.data(data_sig) ,	// input [DATA_WIDTH-1:0] data_sig
	.sr1(sr1_sig) ,	// input [DATA_WIDTH-1:0] sr1_sig
	.sr2(sr2_sig) ,	// input [DATA_WIDTH-1:0] sr2_sig
	.sr3(sr3_sig) ,	// input [DATA_WIDTH-1:0] sr3_sig
	.rd(rd_sig) ,	// input [DATA_WIDTH-1:0] rd_sig
	.pc(pc_sig) ,	// input [DATA_WIDTH-1:0] pc_sig
	.two(two_sig) ,	// input [DATA_WIDTH-1:0] two_sig
	.MEMWRITE(MEMWRITE_sig) ,	// input  MEMWRITE_sig
	.WRITEZERO(WRITEZERO_sig) ,	// input  WRITEZERO_sig
	.clk(clk_sig) ,	// input  clk_sig
	.IRO(IRO_sig) ,	// output [DATA_WIDTH-1:0] IRO_sig
	.IRT(IRT_sig) ,	// output [DATA_WIDTH-1:0] IRT_sig
	.out1(out1_sig) ,	// output [DATA_WIDTH-1:0] out1_sig
	.out2(out2_sig) ,	// output [DATA_WIDTH-1:0] out2_sig
	.out3(out3_sig) 	// output [DATA_WIDTH-1:0] out3_sig
);

defparam Memory_inst.DATA_WIDTH = 16;
defparam Memory_inst.ADDR_WIDTH = 4;
